# Inside of setup.cfg
[metadata]
name = pymusepipe
description-file = Wrapper around MUSE software to reduce MUSE data
author = Eric Emsellem
author-email = eric.emsellem@eso.org
license = mit
long-description = file: README.md
long-description-content-type = text/x-md; charset=UTF-8

# Change if running only on Windows, Mac or Linux (comma-separated)
platforms = any
# Add here all kinds of additional classifiers as defined under
# https://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python

[options]
zip_safe = False
packages = find:
include_package_data = True
package_dir =
    =src
install_requires =
    astropy>=4.0
    mpdaf>=3.5
    numpy>=1.8
    scipy>=1.4.1
    matplotlib>=3.0.0
    reproject>=0.8
    scikit-image>=0.19.3
    spacepylot>=0.0.post1.dev20+g857829b.d20221118
    pymusepipe>=2.26.9
    photutils>=1.2.0
    pypher>=0.6.4

[options.extras_require]
dev =
    pytest
    build
    twine

[options.packages.find]
where = src
exclude =
    tests

[aliases]
dists = bdist_wheel

[build_sphinx]
source_dir = docs/sources
build_dir = docs/build

[flake8]
# Some sane defaults for the code style checker flake8
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py
